# UMAP — Dimensionality Reduction
**Metrics:** Trustworthiness (sklearn proxy)

In [1]:
from utils.dim_reduction import UMAP

import umap
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.manifold import trustworthiness
import numpy as np
import pandas as pd

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779632258.734698  556721 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1779632258.772569  556721 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779632260.136073  556721 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [2]:
digits = load_digits()
X, y = digits.data, digits.target

display(pd.DataFrame(X, columns=[f"pixel_{i}" for i in range(X.shape[1])]).assign(label=y).head())

scaler = StandardScaler()
X = scaler.fit_transform(X)

,pixel_0,pixel_1,pixel_2,pixel_3,pixel_4,pixel_5,pixel_6,pixel_7,pixel_8,pixel_9,...,pixel_55,pixel_56,pixel_57,pixel_58,pixel_59,pixel_60,pixel_61,pixel_62,pixel_63,label
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

In [3]:
model      = UMAP(n_components=2).train(X)
X_embedded = model.predict(X)
report     = model.evaluate(X, X_embedded)
print(f"Embedded shape: {X_embedded.shape}")
for k, v in report.items():
    print(f"{k}: {v}")

display(pd.DataFrame(X_embedded, columns=[f"dim_{i+1}" for i in range(X_embedded.shape[1])]).assign(label=y).head())

/home/sandeep/workspace/learn-ml/.venv/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Embedded shape: (1797, 2)
trustworthiness: 0.9748724386566864
output_shape: [1797, 2]

       dim_1      dim_2  label
0  -3.597611  11.013464      0
1   7.008802  11.829505      1
2   6.515057   9.001987      2
3  10.701493   5.836011      3
4  10.636015  17.444258      4