# t-SNE — Dimensionality Reduction
**Note:** t-SNE is for visualization; no inverse transform.
**Metrics:** KL Divergence

In [1]:
from utils.dim_reduction import TSNE

from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
import pandas as pd

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779632242.337380  556624 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1779632242.366538  556624 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779632243.598109  556624 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [2]:
digits = load_digits()
X, y = digits.data, digits.target

display(pd.DataFrame(X, columns=[f"pixel_{i}" for i in range(X.shape[1])]).assign(label=y).head())

scaler = StandardScaler()
X = scaler.fit_transform(X)

,pixel_0,pixel_1,pixel_2,pixel_3,pixel_4,pixel_5,pixel_6,pixel_7,pixel_8,pixel_9,...,pixel_55,pixel_56,pixel_57,pixel_58,pixel_59,pixel_60,pixel_61,pixel_62,pixel_63,label
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

In [3]:
model      = TSNE(n_components=2, perplexity=30).train(X)
X_embedded = model.predict(X)
report     = model.evaluate(X_embedded)
print(f"Embedded shape: {X_embedded.shape}")
for k, v in report.items():
    print(f"{k}: {v}")

display(pd.DataFrame(X_embedded, columns=[f"dim_{i+1}" for i in range(X_embedded.shape[1])]).assign(label=y).head())

Embedded shape: (1797, 2)
kl_divergence: 0.826017439365387
output_shape: [1797, 2]
n_iter_actual: 999

       dim_1      dim_2  label
0 -43.933941 -36.381721      0
1 -18.166180  -2.729244      1
2   5.112404 -17.671968      2
3  28.663795   5.110395      3
4 -41.376953   4.408359      4