# Principal Component Analysis (PCA)
**Metrics:** Explained Variance Ratio, Reconstruction Error

In [1]:
from utils.dim_reduction import PCA

from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
import pandas as pd

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779632226.737683  556531 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1779632226.771694  556531 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779632228.738480  556531 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [2]:
digits = load_digits()
X, y = digits.data, digits.target

df = pd.DataFrame(X, columns=[f"pixel_{i}" for i in range(X.shape[1])])
df["label"] = y
display(df.head())

scaler = StandardScaler()
X = scaler.fit_transform(X)
print(f"Shape before PCA: {X.shape}")

df_scaled = pd.DataFrame(X, columns=[f"pixel_{i}" for i in range(X.shape[1])])
df_scaled["label"] = y
display(df_scaled.head())

,pixel_0,pixel_1,pixel_2,pixel_3,pixel_4,pixel_5,pixel_6,pixel_7,pixel_8,pixel_9,...,pixel_55,pixel_56,pixel_57,pixel_58,pixel_59,pixel_60,pixel_61,pixel_62,pixel_63,label
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

Shape before PCA: (1797, 64)

,pixel_0,pixel_1,pixel_2,pixel_3,pixel_4,pixel_5,pixel_6,pixel_7,pixel_8,pixel_9,...,pixel_55,pixel_56,pixel_57,pixel_58,pixel_59,pixel_60,pixel_61,pixel_62,pixel_63,label
0,0.0,-0.335016,-0.043081,0.274072,-0.664478,-0.844129,-0.409724,-0.125023,-0.059078,-0.624009,...,-0.209785,-0.023596,-0.299081,0.086719,0.208293,-0.366771,-1.146647,-0.505670,-0.196008,0
1,0.0,-0.335016,-1.094937,0.038648,0.268751,-0.138020,-0.409724,-0.125023,-0.059078,-0.624009,...,-0.209785,-0.023596,-0.299081,-1.089383,-0.249010,0.849632,0.548561,-0.505670,-0.196008,1
2,0.0,-0.335016,-1.094937,-1.844742,0.735366,1.097673,-0.409724,-0.125023,-0.059078,-0.624009,...,-0.209785,-0.023596,-0.299081,-1.089383,-2.078218,-0.164037,1.565686,1.695137,-0.196008,2
3,0.0,-0.335016,0.377661,0.744919,0.268751,-0.844129,-0.409724,-0.125023,-0.059078,1.879691,...,-0.209785,-0.023596,-0.299081,0.282736,0.208293,0.241430,0.379040,-0.505670,-0.196008,3
4,0.0,-0.335016,-1.094937,-2.551014,-0.197863,-1.020657,-0.409724,-0.125023,-0.059078,-0.624009,...,-0.209785,-0.023596,-0.299081,-1.089383,-2.306869,0.849632,-0.468564,-0.505670,-0.196008,4

In [3]:
model     = PCA(n_components=2).train(X)
X_reduced = model.predict(X)
report    = model.evaluate(X)
print(f"Shape after PCA: {X_reduced.shape}")
for k, v in report.items():
    print(f"{k}: {v}")

df_reduced = pd.DataFrame(X_reduced, columns=[f"pc_{i+1}" for i in range(X_reduced.shape[1])])
df_reduced["label"] = y
display(df_reduced.head())

Shape after PCA: (1797, 2)
explained_variance_ratio: [0.12033916097734901, 0.09561054403097888]
total_explained_variance: 0.21594970500832789
reconstruction_error_mse: 0.7472979374139382

       pc_1      pc_2  label
0 -1.914214 -0.954502      0
1 -0.588980  0.924636      1
2 -1.302039 -0.317189      2
3  3.020770 -0.868772      3
4 -4.528949 -1.093480      4